# Generated by Django 4.0.10 on 2023-12-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('billing_unit_number', models.SmallIntegerField()),
                ('billing_street_number', models.SmallIntegerField()),
                ('billing_street_name', models.CharField(max_length=30)),
                ('billing_city', models.CharField(max_length=30)),
                ('billing_state', models.CharField(max_length=2)),
                ('billing_zipcode', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
