# Generated by Django 4.0.10 on 2023-12-08 01:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('billing_unit_number', models.SmallIntegerField()),
                ('billing_street_number', models.SmallIntegerField()),
                ('billing_street_name', models.CharField(max_length=30)),
                ('billing_city', models.CharField(max_length=30)),
                ('billing_state', models.CharField(max_length=2)),
                ('billing_zipcode', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNumber', models.CharField(max_length=30)),
                ('model_property', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('zipcode', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitNumber', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('streetNumber', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('streetName', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('sstate', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('serviceStart', models.DateField()),
                ('squareFootage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('noBedrooms', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('noOccupants', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_label', models.CharField(max_length=30)),
                ('datetimestamp', models.DateTimeField()),
                ('event_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.devices')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Energy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EnergyTimestamp', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.devices')),
            ],
        ),
        migrations.AddConstraint(
            model_name='energyprices',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='positive_price'),
        ),
        migrations.AddConstraint(
            model_name='energyprices',
            constraint=models.UniqueConstraint(fields=('dateTime', 'zipcode'), name='unique_datetime_zipcode'),
        ),
        migrations.AddField(
            model_name='devices',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.devicetype'),
        ),
        migrations.AddField(
            model_name='devices',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicelocations'),
        ),
        migrations.AddField(
            model_name='devices',
            name='modelNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.devicemodel'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.devicetype'),
        ),
        migrations.AddConstraint(
            model_name='servicelocations',
            constraint=models.CheckConstraint(check=models.Q(('unitNumber__gte', 0)), name='unitNumber'),
        ),
        migrations.AddConstraint(
            model_name='servicelocations',
            constraint=models.CheckConstraint(check=models.Q(('streetNumber__gt', 0)), name='streetNumber'),
        ),
        migrations.AddConstraint(
            model_name='servicelocations',
            constraint=models.CheckConstraint(check=models.Q(('noOccupants__gt', 0)), name='noOccupants'),
        ),
        migrations.AddConstraint(
            model_name='servicelocations',
            constraint=models.CheckConstraint(check=models.Q(('noBedrooms__gte', 0)), name='noBedrooms'),
        ),
        migrations.AddConstraint(
            model_name='energyusage',
            constraint=models.UniqueConstraint(fields=('device', 'EnergyTimestamp'), name='unique_device_energy_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='devices',
            constraint=models.CheckConstraint(check=models.Q(('device_id__isnull', False)), name='non_null_device'),
        ),
    ]
