# Generated by Django 4.0.10 on 2023-12-06 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Models',
            new_name='DeviceModel',
        ),
        migrations.RemoveConstraint(
            model_name='devicemodel',
            name='non_null_modelNumber',
        ),
        migrations.AddField(
            model_name='devices',
            name='device_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.devicetype'),
            preserve_default=False,
        ),
    ]
