# Generated by Django 4.0.10 on 2023-12-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
