# Generated by Django 4.0.10 on 2023-12-06 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_devicetype_rename_models_devicemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='device_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.devicetype'),
            preserve_default=False,
        ),
    ]
