# Generated by Django 4.0.10 on 2023-12-06 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_devicemodel_device_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devices',
            old_name='locationID',
            new_name='location',
        ),
    ]
